live_config_reload = true

[colors.bright]
black = "0x565656"
blue = "0x49a4f8"
cyan = "0x99faf2"
green = "0xc0e17d"
magenta = "0xa47de9"
red = "0xec5357"
white = "0xffffff"
yellow = "0xf9da6a"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x2e2e2e"
blue = "0x47a0f3"
cyan = "0x64dbed"
green = "0xabe047"
magenta = "0x7b5cb0"
red = "0xeb4129"
white = "0xe5e9f0"
yellow = "0xf6c744"

[colors.primary]
background = "#0D1117"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#F5F5F5"

[colors.search.focused_match]
background = "#0D1117"
foreground = "#C9CB0A"

[colors.search.matches]
background = "#0D1117"
foreground = "#C9CB0A"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Propo"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Propo"
style = "Regular"

[scrolling]
history = 10000
multiplier = 4

[shell]
args = ["--login"]
program = "/bin/bash"

[window]
decorations = "full"
dynamic_title = false
opacity = 0.95
title = "Alacritty"

[window.dimensions]
columns = 130
lines = 40

[window.padding]
x = 6
y = 6

[window.position]
x = 1198
y = 635
