#!/usr/bin/env python3

# A script to show Memory usage for i3-blocks


import subprocess


def fetch_color(usage_tag: str) -> str:
    usage_colors = {
        "highest_load": "#DC143C",
        "higher_load": "#FF0000",
        "high_load": "#FF4500",
        "moderate_load": "#ADFF2F",
        "low_load": "#32CD32",
        "lower_load": "#228B22",
        "lowest_load": "#008000"
    }

    return usage_colors.get(usage_tag)


def fetch_usage_tag(load_avg: float) -> str:
    if load_avg <= 10:
        return "lowest_load"
    elif load_avg <= 30:
        return "lower_load"
    elif load_avg <= 45:
        return "low_load"
    elif load_avg <= 65:
        return "moderate_load"
    elif load_avg <= 75:
        return "high_load"
    elif load_avg <= 90:
        return "higher_load"
    else:
        return "highest_load"


def fetch_memory_usage():
    memory_info = subprocess.getoutput("free |grep 'Mem'")
    info_list = memory_info.split()
    memory_total = int(info_list[1]) / 1024**2
    memory_used = int(info_list[2]) / 1024**2
    memory_percent= memory_used/memory_total * 100

    return memory_percent, memory_used, memory_total


def generate_usage_string(memory_percent, memory_used, memory_total):
    usage_label = ""
    usage_tag = fetch_usage_tag(memory_percent)
    usage_color = fetch_color(usage_tag)
    message = f"<span color='{usage_color}'>{usage_label} {memory_percent:.2f}%</span>"
    return message


if __name__ == "__main__":
    percent, used, total = fetch_memory_usage()
    msg = generate_usage_string(percent, used, total)
    print(msg)


